   export const prescripts = [
    // === [ 经典短指令：干脆利落的命运判定 ] ===
    "FIND ISHMAEL.",
    "KILL YOUR PAINTING.",
    "CLEAR.",
    "I'M BURGER.",
    "STARE AT A CORNER FOR EXACTLY 300 SECONDS.",    
    "TEAR A BLANK PAGE INTO EXACTLY 17 PIECES.",     
    "WHISPER 'YES' TO THE NEXT PERSON WHO SPEAKS.",  
    "LEAVE A RUSTY COIN ON THE THIRD STAIR.",        
    "DO NOT BLINK WHEN YOU CROSS THE NEXT DOOR.",    

    // === [ 手工与刻印：留痕的仪式 ] ===
    "CARVE A SMILE INTO A RUBBER BLOCK AND BURN IT.",
    "CARVE THE EXACT SHAPE OF YOUR THUMBPRINT ONTO A FRESH RUBBER BLOCK. ONCE COMPLETED, COAT IT WITH BLACK INK AND STAMP IT ON THE NEAREST CONCRETE WALL UNTIL THE INK RUNS DRY.",
    "PRESS RED INK ONTO A BLANK PAGE FOREVER.",

    // === [ 电子与工业：废弃终端的低语 ] ===
    "CUT THE RED WIRE. LEAVE THE BLUE WIRE.",
    "SOLDER EXACTLY 14 COPPER WIRES INTO A PERFECT WEB. CONNECT THE CENTER TO GROUND, AND LET THE ENDS HANG LOOSE. LISTEN TO THE STATIC UNTIL IT SOUNDS LIKE A VOICE.",
    "COUNT THE PINS ON A DEAD MICROCONTROLLER.",
    "STARE AT THE BLANK SCREEN UNTIL IT FLICKERS.",

    // === [ 呼吸与运动：感知肉体的极限 ] ===
    "RUN UNTIL YOUR LUNGS BURN, THEN KEEP WALKING.",
    "LACE YOUR SHOES TIGHTLY AND SPRINT FOR EXACTLY 400 METERS IN THE DEAD OF NIGHT. DO NOT LOOK BACK, EVEN IF YOU HEAR FOOTSTEPS MATCHING YOUR PACE.",
    "HOLD YOUR BREATH AS IF SINKING IN THE LAKE.",
    "COUNT YOUR HEARTBEATS FOR TWO MINUTES.",

    // === [ 垂钓与深渊：等待未知的咬钩 ] ===
    "CAST YOUR LINE WHERE THERE IS NO WATER.",
    "TIE A RUSTY HOOK TO AN INVISIBLE THREAD. WAIT BY THE EDGE OF A MURKY PUDDLE UNTIL YOU FEEL A TUG. DO NOT REEL IT IN. JUST LET GO.",
    "WAIT FOR A BITE ON AN EMPTY HOOK.",

    // === [ 循环与因果：无言的修行 ] ===
    "LIGHT THREE STICKS OF INCENSE IN THE DARK.",
    "WALK CLOCKWISE AROUND THE NEAREST TREE 108 TIMES. WITH EACH STEP, FORGET ONE WORD YOU KNOW. WHEN YOU FINISH, REMAIN SILENT FOR THE REST OF THE DAY.",
    "FLIP THROUGH THE PAGES OF A BOOK YOU HAVE NEVER READ. STOP AT PAGE 199, READ THE FIRST SENTENCE OUT LOUD, AND THEN TEAR THE PAGE OUT.",
    
    // === [ 纯正都市风：诡异的社交交互 ] ===
    "POINT AT THE CEILING AND WHISPER 'YES'.",
    "FIND A STRANGER WEARING A BLUE COAT. HAND THEM A FOLDED PIECE OF PAPER WITH THE WORD 'TOMORROW' WRITTEN ON IT, AND IMMEDIATELY WALK AWAY WITHOUT BLINKING.",

    "HAVE ALL OF YOUR SINNERS TARGET AN ENEMY WITH THE LOWEST HEALTH",
    "SINNERS WITH THE HIGHEST SPEED, TARGET THE SLOWEST ENEMY SLOT",
    "SINNERS WHO ROLLED EVEN-NUMBERED SPEED,CAN ONLY DEAL DAMAGE TO ODD-NUMBERED SLOTS",
    "SINNERS WHO ROLLED ODD-NUMBERED SPEED,CANNOT DEAL DAMAGE TO EVEN-NUMBERED SLOTS",
    "DON'T LET A SINNER TAKE MORE THAN 20 DAMAGE THIS TURN",
    "HAVE YOUR FASTEST SINNERS CLASH WITH THE SLOWEST ENEMY SLOT",
    "HAVE ALL OF YOUR SINNERS TARGET A SINGLE SLOT",
    "USE WINRATE COMMAND THIS TURN",
    "USE DAMAGE COMMAND THIS TURN",
    "ACTIVATE A ABSOLUTE RESONANCE THIS TURN",
    "DON'T USE ANY SKILL 3 THIS TURN",
    "HAVE A SINNER TAKE DAMAGE THIS TURN",
    "USE AN AOE EGO AND HAVE IT ONLY DAMAGE ONE ENEMY OR ONE PART",
    "INFLICT FIVE DIFFERENT DEBUFFS NEXT TURN",
    "HAVE ALL OF YOUR SINNERS USE A DEFENSE SKILL",
    "ACTIVATE A RESONANCE PASSIVE THIS TURN",
    "DEAL AN OVERALL 100 DAMAGE THIS TURN",
    "USE AN E.G.O SKILL THIS TURN",
    "DON'T CLASH WITH ANY OF YOUR SINNERS",
    "DONT'T KILL/STAGGER ANY ENEMIES THIS TURN",
    "REPEAT THE LAST PRESCRIPT",
    "ATTACK WITH SINNERS WITH SPEED TOTALING NO GREATER THAN 14",
    "STAGGER, PART_BREAK, OR DEAL 500 DAMAGE TO AN ENEMY THIS TURN",
    "SINNERS WITH SPEED LOWER OR EQUAL TO 'E', USE AN EGO SKILL",
    "CHAIN ATLEAST 3 SKILL SLOTS WITH THE SAME SIN-AFFINITY",
    "USE AN EGO THAT BUFFS YOUR ENTIRE TEAM THIS OR NEXT TURN",
    "GENERATE FOUR UNIQUE SIN RESOURCES THIS TURN",
    "CHANGE 1 SINNERS RESISTANCE TYPE TO BE FATAL WITH ONE OF THE ENEMIES SKILLS",
    "HAVE A SINNER CORRODE NEXT TURN",
    "HAVE A SINNER DIE NEXT TURN",
    "DON'T USE MORE THAN 2 SKILL_1 THIS TURN",
    "USE AN OVERCLOCK E.G.O THIS TURN AND HAVE THAT SINNER CORRODE THIS OR NEXT TURN",
    "DEAL AN OVERALL 300 DAMAGE THIS TURN",
    "HAVE NO MORE THAN 200 SANITY IN-TOTAL NEXT TURN",
    "HAVE A TOTAL OF 20 STATUS EFFECT [BUFF/DEBUFFS] ON YOUR SINNERS NEXT TURN ",
    "ACTIVATE AN EGO THAT WOULD DIRECTLY/INDIRECTLY KILL AN ALLY ",
    "USE TEN OR MORE SIN RESOURCES THIS TURN",
    "USE AN OVERCLOCK E.G.O THIS TURN",
    "PAT YOUR SLOWEST SINNERS ON THE HEAD FOR 3 SECOND EACH",
    "Uhm... Can you buy me Ice Cream? ~ Sora",
]

